all: prog1 prog2 disparo filw
prog1: esercizio1.cc
	g++ -o $@ $<
prog2: esercizio2.cc
	g++ -o $@ $<
disparo: esercizio3.cc
	g++ -o $@ $<
filw: file.cc
	g++ -o $@ $<
clean:
	rm -f prog1
	rm -f prog2
	rm -f disparo
	rm -f filw